CREATE TABLE data_department.pl
(
    ind integer NOT NULL,
    status text,
    score integer,
    weighted decimal,
    survey_date date,
    outreach_team text,
    interviewer_name text,
    first_name text,
    middle_name text,
    last_name text,
    dob_date date,
    age integer,
    ssn text,
    sleeping_location text,
    loh decimal,
    family_size integer,
    homelessness_documentation text,
    chronic_documentation text,
    disability_documentation text,
    ch_status text,
    dr_date date,
    match_date date,
    housuing_provider text,
    unit_id text,
    housing_type text,
    housed_date date,
    deceased text,
    inactive_date date,
    client_inactive text,
    housed_elsewhere text,
    special_population text,
    last_contact_date text,
    notes text,
    surveycity_daycity_sleepcity text,
    spa text,
    ces_uid text,
    PRIMARY KEY (ind)
);

ALTER TABLE data_department.pl
    OWNER to postgres;
